reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only:[:new, :create]
  resource :session, only:[:new, :create, :destroy]
  resources :subs 
 
  resources :posts, except: [ :index]
  

end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  # validates :post_subs, presence: true


  has_many :post_subs, dependent: :destroy, inverse_of: :post
  
  has_many :subs,
  through: :post_subs,
  source: :sub
  
  belongs_to :author,
  foreign_key: :user_id,
  class_name: :User
  



  


end

reddit_clone/app/models/post_sub.rb
class PostSub < ApplicationRecord
  validates :sub_id, uniqueness: { scope: :post_id}

  belongs_to :post,
  foreign_key: :post_id,
  class_name: :Post

  belongs_to :sub,
  foreign_key: :sub_id,
  class_name: :Sub

end

reddit_clone/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true

  has_many :post_subs, dependent: :destroy, inverse_of: :sub
  
  belongs_to :moderator,
  foreign_key: :user_id,
  class_name: :User

  has_many :posts,
  through: :post_subs,
  source: :post

  

end

reddit_clone/app/models/user.rb
class User < ApplicationRecord

attr_reader :password

validates :password, length: {minimum: 6, allow_nil: true}
validates :session_token, :username, :password_digest, presence: true
after_initialize :ensure_session_token

has_many :subs,
foreign_key: :user_id,
class_name: :Sub


def self.find_by_credentials(username, password)
  user = User.find_by(username: username)
  user && user.is_password?(password) ? user : nil
end

def is_password?(password)
  BCrypt::Password.new(self.password_digest).is_password?(password)
end

def password=(password)
  @password = password
  self.password_digest = BCrypt::Password.create(password)
end

def self.generate_session_token
  SecureRandom.urlsafe_base64(16)
end

def reset_session_token
  self.session_token = self.class.generate_session_token
  self.save!
  self.session_token
end

def ensure_session_token
  self.session_token ||= self.class.generate_session_token
end

end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token
  end

  def sign_out
    #current_user.try(reset_session_token)
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def require_signed_in
    redirect_to new_session_url unless signed_in?
  end

  def require_moderator
    current_user == Sub.find(params[:id]).moderator
  end


end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    

  end

  def create
    @post = Post.new(post_params)
    ps = PostSub.new(post_id: @post.id, sub_id: params[:sub_id])
    ps.save!
    @post.user_id = current_user.id
    @post.sub_id = params[:sub_id]
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id]) 
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end

  end

  def destroy
    @post = Post.find(params[:id]) 
    @post.destroy
    redirect_to sub_url(@post.sub)
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, post_sub_ids: [])
  end

end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user 
      sign_in(user)
      redirect_to subs_url
    else 
      flash[:errors] = ['invalid credentials']
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_signed_in
  before_action :require_moderator, only:[:update, :edit]
  
  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to subs_url
    else 
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else   
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

private
  def sub_params 
    params.require(:sub).permit(:title, :description)
  end
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if signed_in? %>
  <%= current_user.username %>
  <form action="<%= session_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Sign Out">
  </form>
  <% end %>
  
  <%= render 'layouts/errors' %>
  
    <%= yield %>
  </body>
</html>

reddit_clone/app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<form action="<%= post_url(@post) %>" method="post">
<input type="hidden" name="_method" value="PATCH">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<label>
  Title
  <input type="text" name="post[title]" value="<%= @post.title %>">
</label>

<label>
  URL
  <input type="text" name="post[url]" value="<%= @post.url %>">
</label>


<label>
  Content
  <input type="text" name="post[content]" value="<%= @post.content %>">
</label>
<input type="submit" value="Add Post">   

</form>

reddit_clone/app/views/posts/new.html.erb
<h2>New Post</h2>

<form action="<%= posts_url %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<label>
  Title
  <input type="text" name="post[title]" value="">
</label>

<label>
  URL
  <input type="text" name="post[url]" value="">
</label>


<label>
  Content
  <input type="text" name="post[content]" value="">
</label>

<label>Subs</label>
<input type="hidden" name="post[post_sub_ids][]" value=""> 

<% Sub.all.each do |sub|  %>
<label><%= sub.title %>
  <input 
    type="checkbox" 
    value="<%= sub.id %>" 
    name="post[post_sub_ids][]"
    <%= "checked" if @post.post_sub_ids.include?(sub.id) %>
    />
   
</label>
<% end  %>

<input type="submit" value="Add Post">   
</form>

reddit_clone/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<p><%= @post.content %></p>

<form action="<%= edit_post_url(@post) %>" method="GET">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="submit" value="Edit Post">

</form>

reddit_clone/app/views/subs/edit.html.erb
<h2>Edit Sub</h2>

<form action="<%= edit_sub_url %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="hidden" name="_method" value="patch">

<label>
  Title
  <input type="text" name="sub[title]" value="">
</label>

<label>
  Description
  <input type="text" name="sub[description]" value="">
</label>

<input type="submit" value="Edit Sub">   

</form>

reddit_clone/app/views/subs/index.html.erb
<h2>All Subs</h2>

<ul>
<% @subs.each do |sub|  %>
<li>
Title: <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
Description: <%= sub.description %>
</li>
<% end  %>
</ul>

reddit_clone/app/views/subs/new.html.erb
<h2>New Sub</h2>

<form action="<%= subs_url %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<label>
  Title
  <input type="text" name="sub[title]" value="">
</label>

<label>
  Description
  <input type="text" name="sub[description]" value="">
</label>

<input type="submit" value="Create Sub">   

</form>

reddit_clone/app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>

<ul>
<% @sub.posts.each do |post| %>
  <li>
    <a href="<%= post_url(post) %>"><%= post.title %></a>
    <br>
    <%= post.content %>
  </li>
<% end %>
</ul> 

reddit_clone/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<label>
  Username
  <input type="text" name="user[username]" value="">
</label>

<label>
  Password
  <input type="password" name="user[password]" value="">
</label>

<input type="submit" value="Sign Up">   

</form>